language: "python"

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_script:
  - "npm install -g bower"
  - "bower install"

install: "python setup.py install"

script:
  - "python manage.py test --settings=oldsanta.settings"
  - "python manage.py test --settings=newsanta.settings"
